name: Front Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: react build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout Github Action
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: tsc && vite build
        env:
          VITE_URL: ${{ secrets.REACT_APP_API_URI }}

      - name: S3 Deploy
        run: aws s3 cp --recursive --region ap-northeast-2 dist s3://http://game-crew-test.s3-website.ap-northeast-2.amazonaws.com/ --acl bucket-owner-full-control
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
